version: '3.4'

services:
  clothessupplywebcms:
    image: ${DOCKER_REGISTRY}clothessupplywebcms
    build:
      context: .
      dockerfile: ClothesSupplyWebCms\Dockerfile

  clothessupplyapi:
    image: ${DOCKER_REGISTRY}clothessupplyapi
    build:
      context: .
      dockerfile: ClothesSupplyApi\Dockerfile

